#ifndef EEPROMDEF_H_
#define EEPROMDEF_H_

// Fever Mode 
//#define	M_RS485_RX_MODE				GPIO_ResetBits(GPIOA, GPIO_Pin_11)
//#define	M_RS485_TX_MODE				GPIO_SetBits(GPIOA, GPIO_Pin_11)

// EEPROM
#define EEPROM_SIZE                 (EEP_END_ADDRESS - EEP_HEADER)

// EEPROM Data
#define EEP_RESET					0xFF
#define EEP_USED					0xCC

#define EEP_ERROR_CNT				0x08

// EEPROM ADDRESS
#define EEP_HEADER					0x0A

#define EEP_A0				EEP_HEADER + 1
#define EEP_A1				EEP_A0 + 1
#define EEP_A2				EEP_A1 + 1
#define EEP_A3				EEP_A2 + 1
#define EEP_A4				EEP_A3 + 1
#define EEP_A5				EEP_A4 + 1
#define EEP_A6				EEP_A5 + 1
#define EEP_A7				EEP_A6 + 1
#define EEP_A8				EEP_A7 + 1
#define EEP_A9				EEP_A8 + 1
#define EEP_A10				EEP_A9 + 1
#define EEP_A11				EEP_A10 + 1
#define EEP_A12				EEP_A11 + 1
#define EEP_A13				EEP_A12 + 1
#define EEP_A14				EEP_A13 + 1
#define EEP_A15				EEP_A14 + 1
#define EEP_COMM_BAUD_RATE EEP_A15 + 1
#define EEP_END_ADDRESS 	EEP_COMM_BAUD_RATE + 1

// EEP_HW_INFORMATION
#if 0
#define EEP_ENGINE_MODE				EEP_HEADER + 1				    	/*0:iE320 1:uE640 5:iE320M*/
#define EEP_ENGINE_COMM_MODE		EEP_ENGINE_MODE + 1					/*0:I2C 1:USART(iE320M)*/
#define EEP_LENS_TYPE				EEP_ENGINE_COMM_MODE + 1			/*0:NONE 3:SUNNY 150mm 4:Tamron 105mm*/
#define EEP_FRAME_RATE				EEP_LENS_TYPE + 1					/*0:30 1:7.5*/
#define EEP_TPV_SW					EEP_FRAME_RATE + 1					/*0:NORMAL 1:PTV-SW*/
#define EEP_MODEL_NAME				EEP_TPV_SW + 1					/**/
#define EEP_IMAGE_IC				EEP_MODEL_NAME + 1
#define EEP_CAM_ID					EEP_IMAGE_IC + 1					/*1~255*/
#define EEP_TEMP_DETECT_POSSIBLE	EEP_CAM_ID + 1				    	/*Temp Detect Possible*/

// EEP_MENU_IMAGE_ADJUST
#define EEP_AGC_MODE				EEP_TEMP_DETECT_POSSIBLE + 1		/*0:NONE 1:AGC 2:WAGC*/
#define EEP_AGC_CONTRAST			EEP_AGC_MODE + 1					/*0 ~ 255 default 127*/
#define EEP_AGC_BRIGHTNESS			EEP_AGC_CONTRAST + 1				/*0 ~ 255 default 127*/
#define EEP_AGC_LEVEL				EEP_AGC_BRIGHTNESS + 1			    /*0:X1 1:X1.5 2:X2 3:X2.5 4:X3 5:X5 6:X8 7:X15 8:X30*/
#define EEP_AGC_CENTER_POS			EEP_AGC_LEVEL + 1				    /*25~75 (5%)*/
#define EEP_AGC_ROI_SET				EEP_AGC_CENTER_POS + 1			    /*0:FULL, 1:CENTER, 2:UNDER, 3:UPPER, 4:LEFT, 5:RIGHT*/
// #define EEP_AGC_OFFSET				EEP_AGC_ROI_SET + 1				/*0~255*/
// #define EEP_AGC_GAIN                EEP_AGC_OFFSET + 1

#define EEP_MIDE_LEVEL				EEP_AGC_ROI_SET + 1					/*0:OFF 0 ~ 15:MIDE*/
#define EEP_SHARPNESS_LEVEL			EEP_MIDE_LEVEL + 1				/*0:OFF 0 ~ 10:SHARPNESS*/
#define EEP_COLOR_MODE				EEP_SHARPNESS_LEVEL + 1				/*0:GRAY, 1:RAINBOW, 2:IRON, 3:GLOWBOW, 4:2COLOR*/
#define EEP_INVERSE_MODE			EEP_COLOR_MODE + 1				/*0:OFF 1:ON*/
#define EEP_MIRROR_MODE				EEP_INVERSE_MODE + 1				/*0:OFF 1:ON*/
#define EEP_FLIP_MODE				EEP_MIRROR_MODE + 1				/*0:OFF 1:ON*/
#define EEP_FREEZE_MODE				EEP_FLIP_MODE + 1				/*0:OFF 1:ON*/
#define EEP_DZOOM_ENABLE			EEP_FREEZE_MODE + 1				/*0:OFF 1:ON*/
#define EEP_FOCUS_ENABLE			EEP_DZOOM_ENABLE + 1				/*0:OFF 1:ON LENS USE*/
#define EEP_OZOOM_ENABLE			EEP_FOCUS_ENABLE + 1				/*0:OFF 1:ON LENS USE*/
#define EEP_DZOOM_POS				EEP_OZOOM_ENABLE + 1				/*0~15x*/
#define EEP_FOCUS_ENC_H				EEP_DZOOM_POS + 1				/*???*/
#define EEP_FOCUS_ENC_L				EEP_FOCUS_ENC_H + 1
#define EEP_OZOOM_ENC_H				EEP_FOCUS_ENC_L + 1				/*???*/
#define EEP_OZOOM_ENC_L				EEP_OZOOM_ENC_H + 1
#define EEP_FEVER_MODE				EEP_OZOOM_ENC_L + 1				/*???*/

// EEP_MENU_TEMP_DETECT
#define EEP_TEMP_SPOT_POS_X_H		EEP_FEVER_MODE + 1				/*2byte 10data*/
#define EEP_TEMP_SPOT_POS_X_L		EEP_TEMP_SPOT_POS_X_H + 10
#define EEP_TEMP_SPOT_POS_Y_H		EEP_TEMP_SPOT_POS_X_L + 10				/*2byte 10data*/
#define EEP_TEMP_SPOT_POS_Y_L		EEP_TEMP_SPOT_POS_Y_H + 10
#define EEP_TEMP_SPOT_EMISS		    EEP_TEMP_SPOT_POS_Y_L + 10				/*10data*/
#define EEP_TEMP_SPOT_USED_H  		EEP_TEMP_SPOT_EMISS + 10				/*10data*/
#define EEP_TEMP_SPOT_USED_L		EEP_TEMP_SPOT_USED_H + 1

#define EEP_TEMP_DETECT_MODE		EEP_TEMP_SPOT_USED_L + 1				/*0:OFF 1:ON*/
#define EEP_TEC_TEMP				EEP_TEMP_DETECT_MODE + 1				/*0:10, 1:20, 2:30, 3:35, 4:40, 5:50*/
#define EEP_TEMP_AREA_MODE			EEP_TEC_TEMP + 1					/* ???? */
#define EEP_TEMP_HIGH_MODE			EEP_TEMP_AREA_MODE + 1				/*0:NORMAL 1:HIGH*/

#define EEP_TEMP_AREA_LTX_H			EEP_TEMP_HIGH_MODE + 1				/*2byte*/
#define EEP_TEMP_AREA_LTX_L			EEP_TEMP_AREA_LTX_H + 4
#define EEP_TEMP_AREA_LTY_H			EEP_TEMP_AREA_LTX_L + 4				/*2byte*/
#define EEP_TEMP_AREA_LTY_L			EEP_TEMP_AREA_LTY_H + 4				
#define EEP_TEMP_AREA_RBX_H			EEP_TEMP_AREA_LTY_L + 4				/*2byte*/
#define EEP_TEMP_AREA_RBX_L			EEP_TEMP_AREA_RBX_H + 4				
#define EEP_TEMP_AREA_RBY_H			EEP_TEMP_AREA_RBX_L + 4				/*2byte*/
#define EEP_TEMP_AREA_RBY_L			EEP_TEMP_AREA_RBY_H + 4				
#define EEP_TEMP_AREA_EMISS			EEP_TEMP_AREA_RBY_L + 4				/*1~100*/

#define EEP_TEMP_CENTER_MODE		EEP_TEMP_AREA_EMISS + 4				/*0:OFF 1:ON*/
#define EEP_TEMP_CENTER_EMISS		EEP_TEMP_CENTER_MODE + 1				/*1~100*/

#define EEP_HIGH_TEMP_ALARM_H		EEP_TEMP_CENTER_EMISS + 1				/* ��� �˶� */
#define EEP_HIGH_TEMP_ALARM_L		EEP_HIGH_TEMP_ALARM_H + 1
#define EEP_LOW_TEMP_ALARM_H		EEP_HIGH_TEMP_ALARM_L + 1				/* ���� �˶� */
#define EEP_LOW_TEMP_ALARM_L		EEP_LOW_TEMP_ALARM_H + 1				/* ���� �˶� */
#define EEP_SELECT_ALARM			EEP_LOW_TEMP_ALARM_L + 1				/*0:OFF 1:SPOT 2:AREA 3:CENTER 4:ALL*/
#define EEP_ALARM_MODE				EEP_SELECT_ALARM + 1				/*0:LTEMP 1:HTEMP*/
#define EEP_TEMP_OSD                EEP_ALARM_MODE + 1	              	/*0:OFF 1:ON*/
#define EEP_TEMP_OSD_MODE			EEP_TEMP_OSD + 1					/* {0:Default, 1:PTZ, 2:ROI} */

#define EEP_VIDEO_MODE				EEP_TEMP_OSD_MODE + 1				/*0:NTSC 1:PAL*/

// EEP_MENU_COMM_ADJUST
#define EEP_COMM_MODE				EEP_VIDEO_MODE + 1					/*0:UART 1:485*/
#define EEP_COMM_BAUD_RATE			EEP_COMM_MODE + 1					/**/
#define EEP_COMM_OPTION				EEP_COMM_BAUD_RATE + 1				/*N/8/1*/
#define EEP_COMM_PROTOCOL			EEP_COMM_OPTION + 1					/*TPro*/

// EEP_MENU_CALIBRATION
#define EEP_CALI_MODE				EEP_COMM_PROTOCOL + 1				/*Auto interval Manual*/
#define EEP_CALI_INTERVAL_H			EEP_CALI_MODE + 1					/*0~3600*/
#define EEP_CALI_INTERVAL_L			EEP_CALI_INTERVAL_H + 1				/*0~3600*/

// EEP_MENU_INFORMATION
#define EEP_FOV_FOCUS_ENC_H			EEP_CALI_INTERVAL_L + 1				/*FOV Focus Save*/
#define EEP_FOV_FOCUS_ENC_L			EEP_FOV_FOCUS_ENC_H + 5				/*FOV Focus Save*/
#define EEP_FOV_OZOOM_ENC_H			EEP_FOV_FOCUS_ENC_L + 5				/*FOV O-ZOOM Save*/
#define EEP_FOV_OZOOM_ENC_L			EEP_FOV_OZOOM_ENC_H + 5				/*FOV O-ZOOM Save*/

// EEP_SAVE_AGC SETTING For AGC
#define EEP_FOV_AGC_LEVEL			EEP_FOV_OZOOM_ENC_L + 5				/*FOV AGC LEVEL Save*/
#define EEP_FOV_AGC_ROI				EEP_FOV_AGC_LEVEL + 5				/*FOV AGC ROI Save*/
#define EEP_FOV_AGC_MODE			EEP_FOV_AGC_ROI + 5					/*FOV AGC MODE Save*/

// I2C ADDR
#define EEP_I2C_ADDRESS				EEP_FOV_AGC_MODE + 5

#define EEP_TEMP_MARK_HIGH				EEP_I2C_ADDRESS + 1
#define EEP_TEMP_MARK_LOW			EEP_TEMP_MARK_HIGH + 1
// SPECIAL
#define EEP_SPECIAL_DIS			EEP_TEMP_MARK_LOW + 1
#define EEP_SPECIAL_DIS_OFFSET	EEP_SPECIAL_DIS + 1
#define EEP_SPECIAL_DNR			EEP_SPECIAL_DIS_OFFSET + 1
#define EEP_SPECIAL_OUT_RES		EEP_SPECIAL_DNR + 1

#define EEP_COMM_SW_BAUD_RATE	EEP_SPECIAL_OUT_RES + 1
#define EEP_COMM_SW_TERMINATION	EEP_COMM_SW_BAUD_RATE + 1

#define EEP_IP_BOARD_TYPE			EEP_COMM_SW_TERMINATION + 1

#define EEP_MENU_COLOR_TEXT 	EEP_IP_BOARD_TYPE + 1
#define EEP_MENU_COLOR_TEXTH	EEP_MENU_COLOR_TEXT + 1
#define EEP_MENU_COLOR_BG		EEP_MENU_COLOR_TEXTH + 1
#define EEP_MENU_COLOR_BGH		EEP_MENU_COLOR_BG + 1
#define EEP_MENU_POSITION		EEP_MENU_COLOR_BGH + 1

#define EEP_CALI_OSD_ONOFF		EEP_MENU_POSITION + 1

// 170905
#define EEP_SHARPNESS_SHARP		EEP_CALI_OSD_ONOFF + 1

#define EEP_DWDR				EEP_SHARPNESS_SHARP + 1
#define EEP_DWDR_LEVEL			EEP_DWDR + 1
#define EEP_DWDR_STRENGTH		EEP_DWDR_LEVEL + 1

#define EEP_DFOG				EEP_DWDR_STRENGTH + 1
#define EEP_DFOG_LEVEL			EEP_DFOG + 1
#define EEP_DFOG_STRENGTH		EEP_DFOG_LEVEL + 1

#define EEP_BLC					EEP_DFOG_STRENGTH + 1
#define EEP_BLC_DISP			EEP_BLC + 1
#define EEP_BLC_LTX				EEP_BLC_DISP + 1
#define EEP_BLC_LTY				EEP_BLC_LTX + 1
#define EEP_BLC_RBX				EEP_BLC_LTY + 1
#define EEP_BLC_RBY				EEP_BLC_RBX + 1

#define EEP_HLM					EEP_BLC_RBY + 1
#define EEP_HLM_DISP			EEP_HLM + 1
#define EEP_HLM_LEVEL			EEP_HLM_DISP + 1
#define EEP_HLM_LTX				EEP_HLM_LEVEL + 1
#define EEP_HLM_LTY				EEP_HLM_LTX + 1
#define EEP_HLM_RBX				EEP_HLM_LTY + 1
#define EEP_HLM_RBY				EEP_HLM_RBX + 1

#define EEP_AF					EEP_HLM_RBY + 1
#define EEP_AF_DISP				EEP_AF + 1
#define EEP_AF_TABLE_MAX		EEP_AF_DISP + 1
#define EEP_AF_LTX				EEP_AF_TABLE_MAX + 1
#define EEP_AF_LTY				EEP_AF_LTX + 1
#define EEP_AF_RBX				EEP_AF_LTY + 1
#define EEP_AF_RBY				EEP_AF_RBX + 1
#define EEP_AF_IDX				EEP_AF_RBY + 1
#define EEP_AF_CALCULATE		EEP_AF_IDX + 1

#define EEP_FAN_USED			EEP_AF_CALCULATE + 1
#define EEP_FAN_OSD_ONOFF		EEP_FAN_USED + 1

#define EEP_END_ADDRESS 		EEP_FAN_OSD_ONOFF + 1
#endif

// GLOBAL TIME

#endif
